# Generated by Django 4.2.7 on 2024-10-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('resume', models.FileField(upload_to='files/')),
                ('experience', models.IntegerField()),
                ('project_success', models.IntegerField()),
                ('rate', models.IntegerField()),
            ],
        ),
    ]
