# Generated by Django 4.2.7 on 2024-10-22 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
        migrations.RemoveField(
            model_name='about',
            name='resume',
        ),
    ]
